### ISSUE TITLE
TextField - When there is only 1 textfield in Scene, it has its text in black in dark theme when not focused (JAVAFX BUG)

### ISSUE THREAD

**Issue by Ombrelin** [JFXtras/jfxtras-styles#151]
As you can see, when a TextField is next to another input (I tested with PasswordField and Combobox), its content is in black unless focused which in dark theme makes it unreadable.

![image](https://user-images.githubusercontent.com/47502331/79166349-406ba280-7de5-11ea-848f-d2e5fd1a7c33.png)

Code to reproduce : 

```java
public class Main extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Hello World");
        VBox root = new VBox();
        TextField field = new TextField();
        field.setPromptText("TEST");
        root.getChildren().add(field);
        //root.getChildren().add(new PasswordField());
        root.getChildren().add(new Button("Test"));
        root.getChildren().add(new ComboBox<String>());
        Scene scene = new Scene(root, 300, 275);
        JMetro jMetro = new JMetro(Style.DARK);
        jMetro.setScene(scene);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
```

**Comment by dukke** [comment]
The problem seems to actually be related to having only one textfield in a Scene.

**Comment by dukke** [comment]
I've nailed this down to a bug in JavaFX itself (not in JMetro).

The bug manifests itself if you have only 1 Textfield in a Scene and change the skin of that Textfield. You can even change the skin to the same javafx provided skin ("com.sun.javafx.scene.control.skin.TextFieldSkin"). Speculating, perhaps due to some optimization the CSS is not correctly reapplied when that happens.

The workaround is to call `applyCss()` on the textfield, which forces the CSS to be applied.

**Comment by dukke** [comment]
I'm going to close this issue. 
It's a JavaFX bug. Whenever this happens apply the provided workaround.

Thx
