### ISSUE TITLE
Not working with Java Modular Project

### ISSUE THREAD

**Issue by Jackjan4** [JFXtras/jfxtras-styles#18]
If I try to use JMetro in a modular project I get the following error:

Exception in Application start method
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/ButtonSkin

Seems like JMetro (or jfxtras) are using an old path for the ButtonSkin. It shouldnt be com/sun/javafx/scene/control/skin/ButtonSkin. It must be javafx/scene/control/skin/ButtonSkin in a modular project

**Comment by dukke** [comment]
That's correct. It was an oversight since I'm focused on Java 8 support.
I'll have it fixed in the next version.

Thanks.

**Comment by dukke** [comment]
That's correct but JMetro is focused on  working on Java 8 and Java 8 ButtonSkin is still in the com.sun package. JMetro is focused on Java 8 because I haven't had time to create a Java9+ version and Java 8 remains by far the most used Java version according to the latest survey.

If you want Java9+ support consider sponsoring it or alternatively submitting a pull request on a java9+ branch.

**Comment by mrhpn** [comment]
Do I need to use JavaFX sdk 8 as well for JMetro, besides Java 8 ?

**Comment by dukke** [comment]
No. Look at the documentation, JMetro now has support for modules and Java9 and above, check versions 11.x

thx
