### ISSUE TITLE
How to override the css styles?

### ISSUE THREAD

**Issue by bykka** [JFXtras/jfxtras-styles#192]
Hello,

I would like to apply globally another font for my application.
Before I used the next CSS

 `* {
    -fx-font-family: Consolas, monospace;
 }`

but after applying JMetro it does not work anymore.
Does someone have a suggestion on how to change the font? 

here is an example of how it's applied. And of cause, I tried to add 'global.css' in a different order.
![image](https://user-images.githubusercontent.com/489997/114096272-ca4a3080-98be-11eb-8ccb-420ba915200a.png)

**Comment by dukke** [comment]
Please check JMetro documentation page: https://pixelduke.com/java-javafx-theme-jmetro/ check the section "Not like Modena".

Also check the JMetro stylesheet, namely base.css. You need to make sure your rules have a higher or equal specificity than the rules set by JMetro. If they have equal they need to come afterwards in order to override the ones from JMetro. 
In the JMetro stylesheet search for every time there is a font-family definition and make sure you override them in your rules (through a higher or equal specificity).
