### ISSUE TITLE
Radio-Button not correct color on mouse hover.

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#20]
### Describe the bug
> - Incorrect color change behavior when hovering over RadioButton when it was turned off after being turned on.

### Steps to reproduce the behavior
> 1. Add radio-button to your scene.
> 2. Set Focus Traversable to true.
> 3. Click on or check radio-button.
> 4. Uncheck your radio-button.
> 5. Now. Hover on radio-button and see issue.

### Materials
> ![metroradiobuttonissue](https://user-images.githubusercontent.com/39625750/50053961-c58d6b80-014d-11e9-8321-939e7a924fd5.gif)

### Environment information
> - JMetro version: [5.0.0]
> - System: [Windows 10 1803 x64]
> - Java Runtime Environment: [1.8.0_171]

**Comment by dukke** [comment]
Hi Pavel, thanks for the error report.

One thing:

- I don't think Radio Buttons are supposed to be "unchecked". A Radio Button needs to be part of a group, so that one option is always selected. If you select another Radio Button on the group the previous selected Radio Button get's "unchecked". That's the only way you normally have of unselecting a Radio Button.

Having said that, this issue is fixed in version 5.0.1. It was an easy fix.

Thanks,

**Comment by dukke** [comment]
..Nevertheless the problem might still happen even with the Group assigned to the Radio Buttons so thank you for reporting this issue. The problem, I believe, when the focus traversal is set to true.

**Comment by MairwunNx** [comment]
Yes, when focus traversal is true, no problems, good luck with fixing! :+1:

**Comment by MairwunNx** [comment]
No problem @dukke :) Thanks for good library and css styles!
