### ISSUE TITLE
Problem with Windows 10 Title bar

### ISSUE THREAD

**Issue by se7kn8** [JFXtras/jfxtras-styles#201]
JMetroVersion: 11.6.15
Java Version: 16.0.1
JavaFX Version: 16
OS: Windows 10 21h1

Expected look:
![grafik](https://user-images.githubusercontent.com/35075354/120680058-2c2bae80-c49a-11eb-8525-dfca1a39749b.png)

How it looks when the Windows 10 Option "Show accent colour on title bars" is enabled:
![grafik](https://user-images.githubusercontent.com/35075354/120680261-639a5b00-c49a-11eb-98e3-6ce278540c0c.png)

Maybe it would help to make the icon transparent and add some margin between the header text and the title bar.

**Comment by dukke** [comment]
Hi @SE7-KN8 

Yeah I'm not sure that's possible. I don't remember exactly but I think the only option was to set a white icon so that the icon seems as if it is not showing.
If this is the case then the only solution might be to create new Dialog controls that replace the standard ones from JavaFX. I would probably make them available in the FXSkins library than style them on JMetro.

**Comment by dukke** [comment]
As stated, there's no way to fix this in JMetro unfortunately. 
You can't provide a transparent icon to a window. 

The only solution I see is for you to have an icon with a solid color painted on it. That color would be the same as the color of the title bar.

You would also have to add the margin yourself as on a standard window (all white) that margin would look bad.

**Comment by dukke** [comment]
Closing this issue..
