### ISSUE TITLE
Add Maven/Gradle coordinates to README

### ISSUE THREAD

**Issue by AlmasB** [JFXtras/jfxtras-styles#204]
These are already available from https://pixelduke.com/java-javafx-theme-jmetro/ but adding these to README directly will simplify using jmetro as an external library.

**Comment by dukke** [comment]
Hi @AlmasB 

Truly sorry for the late reply but been very busy with my day to day work.

Thanks for the suggestion, it makes a lot of sense but I'd prefer to keep the documentation all in one place as much as possible (it's easier to maintain the documentation that way).

Feel free do debate this further if you think it's really important to have this in github or you know of situations where people got confused and were unable to use JMetro because of this.

**Comment by dukke** [comment]
On second thought I think you are right. This should probably be in the readme, in github, as it is the bare minimum to get the library,
