### ISSUE TITLE
Set background colors for layout panes (BorderPane, etc) according to Style value. Also set them for Toolbar, ScrollPane, controls, etc

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#39]
Dark theme: 

![image](https://user-images.githubusercontent.com/39625750/52003361-57222400-24d5-11e9-98b4-0579279e84ea.png)

After adding background style property:

![image](https://user-images.githubusercontent.com/39625750/52003380-673a0380-24d5-11e9-907f-e05cce1d8d15.png)

![image](https://user-images.githubusercontent.com/39625750/52003387-6ef9a800-24d5-11e9-9861-e83f39ca0f1b.png)

I think it needed to do automatically, right? Because, new people who want to use your lib and themes, want what all controls be themed, right? Then need it do automatically, it no hard, just add background prop to it elements. just then theme applied to all controls needed, i think you understand me :)

additional ui elements needed to automatically background color: `[ "Pane", "Anchor Pane", "Scroll Pane", "Scroll Pane Empty", "ToolBar"]`

**Comment by MairwunNx** [comment]
@dukke OK ,if you think what I think right, than I try realize it in pull request :) or you can it make self

**Comment by MairwunNx** [comment]
resolved in #42 , please @dukke review my changes, i already it done. :)

**Comment by dukke** [comment]
I've changed the title of this issue.
There's a deeper problem with background colors not just for layout panes, scrollpane and toolbar. 

Changing the default layout panes background colors will also change the background for other controls since some of them make use of these layout panes, so after changing the default layout panes background colors some controls backgrounds need to be corrected.

**Comment by dukke** [comment]
Fixed.
